COLUMNS:
  date: object
  temperature_2m: float64
  relative_humidity_2m: float64
  dew_point_2m: float64
  apparent_temperature: float64
  precipitation: float64
  weather_code: float64
  cloud_cover: float64
  cloud_cover_low: float64
  rain: float64
  surface_pressure: float64
  cloud_cover_mid: float64
  cloud_cover_high: float64
  wind_speed_10m: float64
  wind_speed_100m: float64
  wind_direction_10m: float64
  wind_direction_100m: float64
  wind_gusts_10m: float64

TARGET:
  name: temperature_2m
